[GNSS-SDR]

; ####################################################
; SIGNAL SOURCE
; ####################################################

GNSS-SDR.internal_fs_sps=5000000
SignalSource.implementation=File_Signal_Source
SignalSource.filename=/data/clear_sky_500mb.bin

#SignalSource.item_type=float
SignalSource.item_type=ishort

SignalSource.sampling_frequency=25000000

SignalSource.samples=0
SignalSource.repeat=false

; ####################################################
; DATA TYPE ADAPTER
; ####################################################

#DataTypeAdapter.implementation=Ifloat_To_Complex
DataTypeAdapter.implementation=Ishort_To_Complex

; ####################################################
; INPUT FILTER
; ####################################################

InputFilter.implementation=Freq_Xlating_Fir_Filter

InputFilter.input_item_type=gr_complex
InputFilter.output_item_type=gr_complex

InputFilter.decimation_factor=5

; 25 MHz / 5 = 5 MHz

InputFilter.filter_type=lowpass

InputFilter.taps_item_type=float

InputFilter.number_of_taps=64

InputFilter.band1_begin=0.0
InputFilter.band1_end=2500000.0

InputFilter.ampl1_begin=1.0
InputFilter.ampl1_end=1.0

; ####################################################
; SIGNAL CONDITIONER
; ####################################################

SignalConditioner.implementation=Signal_Conditioner

; ####################################################
; CHANNELS
; ####################################################

Channels_1C.count=8

Channel.signal=1C

; ####################################################
; ACQUISITION
; ####################################################

Acquisition_1C.implementation=GPS_L1_CA_PCPS_Acquisition

Acquisition_1C.item_type=gr_complex

Acquisition_1C.pfa=0.01

Acquisition_1C.doppler_max=6000
Acquisition_1C.doppler_step=500

Acquisition_1C.coherent_integration_time_ms=1

; ####################################################
; TRACKING
; ####################################################

Tracking_1C.implementation=GPS_L1_CA_DLL_PLL_Tracking

Tracking_1C.item_type=gr_complex

Tracking_1C.dump=true
Tracking_1C.dump_filename=/output/tracking.dat

Tracking_1C.dump_interval_ms=10
Tracking_1C.dump_correlation=true

; ####################################################
; TELEMETRY DECODER
; ####################################################

TelemetryDecoder_1C.implementation=GPS_L1_CA_Telemetry_Decoder

; ####################################################
; OBSERVABLES
; ####################################################

Observables.implementation=Hybrid_Observables
Observables.dump=true
Observables.dump_filename=/output/observables.dat

; ####################################################
; PVT
; ####################################################

PVT.implementation=RTKLIB_PVT